// Fallback species pool used when no EBIRD_API_KEY is configured, so the
// app is fully playable without live keys (matches the old app's "demo
// mode" spirit). Real eBird species codes are used throughout so nothing
// changes structurally once a key is added — this list just stops being
// the source and eBird's live region lookup takes over.
export const DEMO_SPECIES = [
  { code: 'amerob', commonName: 'American Robin', sciName: 'Turdus migratorius',
    fieldMark: 'A medium songbird with a warm brick-orange breast, a dark gray-brown back, and a yellow bill.',
    habitat: 'Common on lawns and in gardens across nearly all of North America, often seen tugging earthworms from the ground.' },
  { code: 'norcar', commonName: 'Northern Cardinal', sciName: 'Cardinalis cardinalis',
    fieldMark: 'A bright red bird with a pointed crest and a thick orange-red bill; females are warm tan with red highlights.',
    habitat: 'A year-round resident of the eastern and central United States, favoring shrubby edges and backyard feeders.' },
  { code: 'blujay', commonName: 'Blue Jay', sciName: 'Cyanocitta cristata',
    fieldMark: 'A large, crested songbird in bold blue, white, and black, with a loud, harsh call.',
    habitat: 'Found in forests and suburban yards across eastern and central North America; known for mimicking hawk calls.' },
  { code: 'amecro', commonName: 'American Crow', sciName: 'Corvus brachyrhynchos',
    fieldMark: 'An all-black bird, larger than a jay, with a heavy bill and a distinctive flat-toned "caw."',
    habitat: 'Highly adaptable, found nearly everywhere across North America from farmland to city parks.' },
  { code: 'houfin', commonName: 'House Finch', sciName: 'Haemorhous mexicanus',
    fieldMark: 'A small finch; males show a rosy red face and breast, females are streaky brown all over.',
    habitat: 'Extremely common at feeders across the continent; forms small chattering flocks.' },
  { code: 'daejun', commonName: 'Dark-eyed Junco', sciName: 'Junco hyemalis',
    fieldMark: 'A small sparrow-like bird, slate-gray above and white below, with a pink bill and white outer tail feathers that flash in flight.',
    habitat: 'A common winter visitor across much of the U.S., often called the "snowbird" for arriving with cold weather.' },
  { code: 'mourdo', commonName: 'Mourning Dove', sciName: 'Zenaida macroura',
    fieldMark: 'A slim, soft grayish-brown dove with a small head, a long pointed tail, and black spots on the wings.',
    habitat: 'Common in open country and suburbs continent-wide; named for its soft, mournful cooing call.' },
  { code: 'dowwoo', commonName: 'Downy Woodpecker', sciName: 'Dryobates pubescens',
    fieldMark: 'A small black-and-white woodpecker with a short bill; males have a small red patch on the back of the head.',
    habitat: 'North America’s smallest woodpecker, common in woodlots and backyards, often at suet feeders.' },
  { code: 'whbnut', commonName: 'White-breasted Nuthatch', sciName: 'Sitta carolinensis',
    fieldMark: 'A compact bird with a blue-gray back, white face and breast, and a habit of creeping headfirst down tree trunks.',
    habitat: 'A year-round resident of deciduous forests and wooded neighborhoods across most of the U.S.' },
  { code: 'carwre', commonName: 'Carolina Wren', sciName: 'Thryothorus ludovicianus',
    fieldMark: 'A small, round, rich reddish-brown bird with a bold white eyebrow stripe and a cocked-up tail.',
    habitat: 'A loud singer for its size, found in tangled brush and gardens across the southeastern and central U.S.' },
  { code: 'sonspa', commonName: 'Song Sparrow', sciName: 'Melospiza melodia',
    fieldMark: 'A streaky brown sparrow with a central breast spot formed by converging streaks, and a habit of pumping its tail in flight.',
    habitat: 'One of the most widespread sparrows in North America, found in brushy edges near water almost everywhere.' },
  { code: 'comgra', commonName: 'Common Grackle', sciName: 'Quiscalus quiscula',
    fieldMark: 'A large, glossy blackbird with an iridescent purple-blue head, pale yellow eyes, and a long, wedge-shaped tail.',
    habitat: 'Common in open fields, lawns, and city parks across the eastern and central U.S., often in noisy flocks.' },
  { code: 'redwin', commonName: 'Red-winged Blackbird', sciName: 'Agelaius phoeniceus',
    fieldMark: 'Males are glossy black with bold red-and-yellow shoulder patches; females are heavily streaked brown, almost sparrow-like.',
    habitat: 'One of the most abundant birds in North America, nesting in marshes and wet fields, with a distinctive "conk-la-ree" song.' },
  { code: 'baleag', commonName: 'Bald Eagle', sciName: 'Haliaeetus leucocephalus',
    fieldMark: 'A huge raptor with a white head and tail contrasting a dark brown body; juveniles are mottled brown and take years to gain the white head.',
    habitat: 'Found near large lakes, rivers, and coastlines across North America; numbers have rebounded strongly since the mid-1900s.' },
  { code: 'grhowl', commonName: 'Great Horned Owl', sciName: 'Bubo virginianus',
    fieldMark: 'A large, powerful owl with prominent ear tufts, yellow eyes, and mottled gray-brown plumage.',
    habitat: 'One of the most widespread owls in the Americas, at home in forests, deserts, and even city parks; famous for its deep "hoo-h\'HOO-hoo-hoo" call.' },
  { code: 'ribgul', commonName: 'Ring-billed Gull', sciName: 'Larus delawarensis',
    fieldMark: 'A medium gull, pale gray above and white below, with a black ring encircling the tip of its yellow bill.',
    habitat: 'Common around lakes, parking lots, and landfills across North America — the "parking lot gull."' },
  { code: 'ruthum', commonName: 'Ruby-throated Hummingbird', sciName: 'Archilochus colubris',
    fieldMark: 'A tiny, iridescent green bird; males flash a brilliant ruby-red throat patch in the right light.',
    habitat: 'The only hummingbird breeding in eastern North America, drawn to tubular flowers and sugar-water feeders.' },
  { code: 'easblu', commonName: 'Eastern Bluebird', sciName: 'Sialia sialis',
    fieldMark: 'A small thrush with vivid blue upperparts and a warm rusty-orange breast; females are duller with a hint of blue in the wings and tail.',
    habitat: 'Found in open country with scattered trees across the eastern U.S., often nesting in roadside boxes put up just for them.' },
];
